// Sample catalogue loaded by scripts/db/seed.ts. Shapes mirror the schema (RFD §8).
// Replace with real products through the admin portal (Phase 3).

export interface ProductRow {
  code: string;
  name: string;
  categorySlug: string;
  fabric: string;
  colour: string;
  description: string;
  work: string;
  lengthIn: number | null;
  setIncludes: string;
  washCare: string;
  ratePaise: number;
  mrpPaise: number;
  moq: number;
  stockPcs: number;
  sizes: string[];
  isVisible: boolean;
  isTrending: boolean;
  newUntil: string | null; // ISO date
  popularity: number; // pcs enquired in last 30 d
  createdAt: string;
  imageCount: number;
}

export interface CategoryRow {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  showOnHome: boolean;
  isVisible: boolean;
  sortOrder: number;
}

export const categories: CategoryRow[] = [
  {
    slug: "kurtis",
    name: "Kurtis",
    shortName: "Kurtis",
    description: "Straight, flared and A-line kurtis in rayon, cotton and blends.",
    showOnHome: true,
    isVisible: true,
    sortOrder: 1,
  },
  {
    slug: "kurti-with-pant",
    name: "Kurti with Pant",
    shortName: "Kurti + Pant",
    description: "Matching kurti and pant sets for daily and office wear.",
    showOnHome: true,
    isVisible: true,
    sortOrder: 2,
  },
  {
    slug: "kurti-with-dupatta",
    name: "Kurti with Dupatta",
    shortName: "With Dupatta",
    description: "Festive kurtis paired with woven and printed dupattas.",
    showOnHome: true,
    isVisible: true,
    sortOrder: 3,
  },
  {
    slug: "suit-sets",
    name: "3-Piece Suit Sets",
    shortName: "3-Piece",
    description: "Kurti, pant and dupatta sets for festive and wedding season.",
    showOnHome: true,
    isVisible: true,
    sortOrder: 4,
  },
  {
    slug: "co-ord-sets",
    name: "Co-ord Sets",
    shortName: "Co-ord",
    description: "Hidden until stock arrives.",
    showOnHome: false,
    isVisible: false,
    sortOrder: 5,
  },
];

export const fabrics = ["Rayon", "Cotton", "Chanderi", "Georgette", "Silk Blend", "Organza"];
export const colours = ["Maroon", "Bottle Green", "Navy Blue", "Mustard", "Teal", "Peach", "Pink", "Black"];

const d = (daysFromToday: number) => {
  const t = new Date();
  t.setDate(t.getDate() + daysFromToday);
  return t.toISOString().slice(0, 10);
};

const all = ["S", "M", "L", "XL", "XXL", "3XL"];

export const products: ProductRow[] = [
  {
    code: "SN-101",
    name: "Royal Maroon Heavy Embroidered Straight Kurti Set",
    categorySlug: "suit-sets",
    fabric: "Rayon",
    colour: "Maroon",
    description:
      "Exquisite straight-cut rayon kurti with zardozi and thread embroidery on the yoke, paired with matching pants. Festive best-seller that repeats every season.",
    work: "Zardozi + thread",
    lengthIn: 44,
    setIncludes: "Kurti + pant",
    washCare: "Dry clean",
    ratePaise: 125000,
    mrpPaise: 249900,
    moq: 3,
    stockPcs: 128,
    sizes: ["M", "L", "XL", "XXL"],
    isVisible: true,
    isTrending: true,
    newUntil: d(10),
    popularity: 186,
    createdAt: d(-4),
    imageCount: 2,
  },
  {
    code: "SN-102",
    name: "Teal Blue Floral Printed Kurti with Pant",
    categorySlug: "kurti-with-pant",
    fabric: "Cotton",
    colour: "Teal",
    description:
      "Daily-wear teal blue cotton kurti with digital floral print and pocket detailing on the pant. Sells well for office and casual wear.",
    work: "Digital print",
    lengthIn: 42,
    setIncludes: "Kurti + pant",
    washCare: "Hand wash cold",
    ratePaise: 85000,
    mrpPaise: 169900,
    moq: 3,
    stockPcs: 240,
    sizes: all,
    isVisible: true,
    isTrending: true,
    newUntil: d(8),
    popularity: 117,
    createdAt: d(-6),
    imageCount: 1,
  },
  {
    code: "SN-103",
    name: "Pastel Peach Festive Kurti with Dupatta",
    categorySlug: "kurti-with-dupatta",
    fabric: "Chanderi",
    colour: "Peach",
    description:
      "Graceful pastel peach Chanderi kurti with a matching woven dupatta finished in golden zari borders. A festive collection favourite.",
    work: "Zari border",
    lengthIn: 46,
    setIncludes: "Kurti + dupatta",
    washCare: "Dry clean",
    ratePaise: 110000,
    mrpPaise: 219900,
    moq: 3,
    stockPcs: 14,
    sizes: ["M", "L", "XL"],
    isVisible: true,
    isTrending: true,
    newUntil: null,
    popularity: 64,
    createdAt: d(-30),
    imageCount: 1,
  },
  {
    code: "SN-104",
    name: "Emerald Green Gold Foil Print Flared Kurti",
    categorySlug: "kurtis",
    fabric: "Rayon",
    colour: "Bottle Green",
    description:
      "Flowy emerald green rayon kurti with gold foil ethnic motifs all over. Consistent quality that brings repeat customers.",
    work: "Gold foil print",
    lengthIn: 48,
    setIncludes: "Kurti only",
    washCare: "Hand wash cold",
    ratePaise: 95000,
    mrpPaise: 189900,
    moq: 3,
    stockPcs: 96,
    sizes: ["S", "M", "L", "XL", "XXL"],
    isVisible: true,
    isTrending: false,
    newUntil: d(12),
    popularity: 98,
    createdAt: d(-2),
    imageCount: 1,
  },
  {
    code: "SN-105",
    name: "Navy Blue Anarkali 3-Piece Suit Set",
    categorySlug: "suit-sets",
    fabric: "Silk Blend",
    colour: "Navy Blue",
    description:
      "Navy blue silk-blend anarkali with gota patti work on the neckline and sleeves. Complete 3-piece set with pant and dupatta.",
    work: "Gota patti",
    lengthIn: 50,
    setIncludes: "Kurti + pant + dupatta",
    washCare: "Dry clean",
    ratePaise: 135000,
    mrpPaise: 269900,
    moq: 3,
    stockPcs: 62,
    sizes: ["M", "L", "XL", "XXL", "3XL"],
    isVisible: true,
    isTrending: true,
    newUntil: null,
    popularity: 72,
    createdAt: d(-20),
    imageCount: 1,
  },
  {
    code: "SN-106",
    name: "Classic Black Rayon Daily Wear Kurti",
    categorySlug: "kurtis",
    fabric: "Rayon",
    colour: "Black",
    description:
      "Super soft 14 kg rayon plain black kurti with a designer wooden-button placket. A staple that sells year-round in every boutique.",
    work: "Button placket",
    lengthIn: 44,
    setIncludes: "Kurti only",
    washCare: "Machine wash",
    ratePaise: 65000,
    mrpPaise: 129900,
    moq: 5,
    stockPcs: 410,
    sizes: ["S", "M", "L", "XL", "XXL"],
    isVisible: true,
    isTrending: true,
    newUntil: null,
    popularity: 142,
    createdAt: d(-45),
    imageCount: 1,
  },
  {
    code: "SN-107",
    name: "Mustard Cotton Straight Kurti",
    categorySlug: "kurtis",
    fabric: "Cotton",
    colour: "Mustard",
    description:
      "Bright mustard cotton straight kurti with contrast piping. Light, breathable and easy to sell in summer.",
    work: "Contrast piping",
    lengthIn: 44,
    setIncludes: "Kurti only",
    washCare: "Machine wash",
    ratePaise: 72000,
    mrpPaise: 144900,
    moq: 3,
    stockPcs: 0,
    sizes: ["S", "M", "L", "XL"],
    isVisible: true,
    isTrending: false,
    newUntil: null,
    popularity: 12,
    createdAt: d(-60),
    imageCount: 0,
  },
  {
    code: "SN-108",
    name: "Pink Georgette Printed Kurti with Dupatta",
    categorySlug: "kurti-with-dupatta",
    fabric: "Georgette",
    colour: "Pink",
    description: "Soft pink georgette kurti with all-over floral print and a lightweight chiffon dupatta.",
    work: "Floral print",
    lengthIn: 46,
    setIncludes: "Kurti + dupatta",
    washCare: "Dry clean",
    ratePaise: 98000,
    mrpPaise: 195900,
    moq: 3,
    stockPcs: 75,
    sizes: ["M", "L", "XL", "XXL"],
    isVisible: true,
    isTrending: false,
    newUntil: d(5),
    popularity: 40,
    createdAt: d(-9),
    imageCount: 1,
  },
  {
    code: "SN-109",
    name: "Maroon Chanderi Kurti with Palazzo",
    categorySlug: "kurti-with-pant",
    fabric: "Chanderi",
    colour: "Maroon",
    description: "Rich maroon Chanderi kurti with gold butti weave, paired with a flared palazzo.",
    work: "Butti weave",
    lengthIn: 44,
    setIncludes: "Kurti + palazzo",
    washCare: "Dry clean",
    ratePaise: 115000,
    mrpPaise: 229900,
    moq: 3,
    stockPcs: 58,
    sizes: ["M", "L", "XL", "XXL"],
    isVisible: true,
    isTrending: false,
    newUntil: null,
    popularity: 33,
    createdAt: d(-25),
    imageCount: 1,
  },
  {
    code: "SN-110",
    name: "Bottle Green Organza 3-Piece Festive Set",
    categorySlug: "suit-sets",
    fabric: "Organza",
    colour: "Bottle Green",
    description:
      "Bottle green organza kurti with sequin and resham work, with matching pant and embroidered organza dupatta.",
    work: "Sequin + resham",
    lengthIn: 48,
    setIncludes: "Kurti + pant + dupatta",
    washCare: "Dry clean",
    ratePaise: 165000,
    mrpPaise: 329900,
    moq: 3,
    stockPcs: 40,
    sizes: ["M", "L", "XL", "XXL"],
    isVisible: true,
    isTrending: false,
    newUntil: d(13),
    popularity: 21,
    createdAt: d(-1),
    imageCount: 1,
  },
  {
    code: "SN-111",
    name: "Navy Printed Rayon A-Line Kurti",
    categorySlug: "kurtis",
    fabric: "Rayon",
    colour: "Navy Blue",
    description:
      "Navy rayon A-line kurti with white bandhani-style print. Everyday best-seller at an easy price point.",
    work: "Bandhani print",
    lengthIn: 42,
    setIncludes: "Kurti only",
    washCare: "Machine wash",
    ratePaise: 55000,
    mrpPaise: 109900,
    moq: 5,
    stockPcs: 300,
    sizes: all,
    isVisible: true,
    isTrending: false,
    newUntil: null,
    popularity: 88,
    createdAt: d(-35),
    imageCount: 1,
  },
  {
    code: "SN-112",
    name: "Peach Cotton Kurti with Printed Pant",
    categorySlug: "kurti-with-pant",
    fabric: "Cotton",
    colour: "Peach",
    description: "Solid peach cotton kurti with lace detailing, paired with a printed straight pant.",
    work: "Lace detailing",
    lengthIn: 42,
    setIncludes: "Kurti + pant",
    washCare: "Hand wash cold",
    ratePaise: 78000,
    mrpPaise: 155900,
    moq: 3,
    stockPcs: 120,
    sizes: ["S", "M", "L", "XL", "XXL"],
    isVisible: true,
    isTrending: false,
    newUntil: null,
    popularity: 27,
    createdAt: d(-40),
    imageCount: 1,
  },
  {
    code: "SN-113",
    name: "Teal Silk Blend Kurti with Banarasi Dupatta",
    categorySlug: "kurti-with-dupatta",
    fabric: "Silk Blend",
    colour: "Teal",
    description: "Teal silk-blend kurti with a Banarasi-weave dupatta. Wedding-season piece with a rich fall.",
    work: "Banarasi weave",
    lengthIn: 46,
    setIncludes: "Kurti + dupatta",
    washCare: "Dry clean",
    ratePaise: 145000,
    mrpPaise: 289900,
    moq: 3,
    stockPcs: 36,
    sizes: ["M", "L", "XL"],
    isVisible: true,
    isTrending: false,
    newUntil: null,
    popularity: 19,
    createdAt: d(-15),
    imageCount: 1,
  },
  {
    code: "SN-114",
    name: "Black Georgette Embroidered 3-Piece Set",
    categorySlug: "suit-sets",
    fabric: "Georgette",
    colour: "Black",
    description: "Black georgette kurti with contrast gold thread embroidery, straight pant and net dupatta.",
    work: "Thread embroidery",
    lengthIn: 46,
    setIncludes: "Kurti + pant + dupatta",
    washCare: "Dry clean",
    ratePaise: 128000,
    mrpPaise: 255900,
    moq: 3,
    stockPcs: 50,
    sizes: ["M", "L", "XL", "XXL", "3XL"],
    isVisible: true,
    isTrending: false,
    newUntil: null,
    popularity: 30,
    createdAt: d(-18),
    imageCount: 1,
  },
  {
    code: "SN-115",
    name: "Pink Rayon Flared Kurti with Mirror Work",
    categorySlug: "kurtis",
    fabric: "Rayon",
    colour: "Pink",
    description: "Rani pink rayon flared kurti with mirror work on the yoke. Popular for Navratri.",
    work: "Mirror work",
    lengthIn: 46,
    setIncludes: "Kurti only",
    washCare: "Hand wash cold",
    ratePaise: 82000,
    mrpPaise: 163900,
    moq: 3,
    stockPcs: 90,
    sizes: ["S", "M", "L", "XL", "XXL"],
    isVisible: true,
    isTrending: false,
    newUntil: d(11),
    popularity: 45,
    createdAt: d(-3),
    imageCount: 1,
  },
  {
    code: "SN-116",
    name: "Mustard Chanderi Kurti with Pant (hidden)",
    categorySlug: "kurti-with-pant",
    fabric: "Chanderi",
    colour: "Mustard",
    description: "Hidden draft product. Must never appear on the storefront.",
    work: "",
    lengthIn: null,
    setIncludes: "Kurti + pant",
    washCare: "Dry clean",
    ratePaise: 99000,
    mrpPaise: 199000,
    moq: 3,
    stockPcs: 20,
    sizes: ["M", "L"],
    isVisible: false,
    isTrending: true,
    newUntil: d(10),
    popularity: 0,
    createdAt: d(0),
    imageCount: 1,
  },
];

// Colour swatches used by placeholder product images (real photos come from the DB in Phase 2).
export const colourHex: Record<string, string> = {
  Maroon: "#6B1F2B",
  "Bottle Green": "#1F4D3A",
  "Navy Blue": "#1E2A4A",
  Mustard: "#C9962E",
  Teal: "#1D6B6B",
  Peach: "#E8A987",
  Pink: "#C94F7C",
  Black: "#2B1B1C",
};
