// Quick-pick shades common in ethnic wear, offered when adding a new colour.
// Any other shade can still be chosen with the free colour picker.
export const COLOUR_PRESETS: { name: string; hex: string }[] = [
  { name: "Red", hex: "#C0282D" },
  { name: "Wine", hex: "#5E1A2A" },
  { name: "Rani Pink", hex: "#D6246E" },
  { name: "Baby Pink", hex: "#F4B6C8" },
  { name: "Magenta", hex: "#A3195B" },
  { name: "Onion Pink", hex: "#E7A6A1" },
  { name: "Rust", hex: "#A8492A" },
  { name: "Orange", hex: "#E8742A" },
  { name: "Coral", hex: "#F07A62" },
  { name: "Yellow", hex: "#F2C230" },
  { name: "Lemon", hex: "#EEE27A" },
  { name: "Gold", hex: "#C9A13B" },
  { name: "Olive", hex: "#6B6B2A" },
  { name: "Mehendi Green", hex: "#6E7F2E" },
  { name: "Parrot Green", hex: "#5DB33B" },
  { name: "Mint", hex: "#A8DBC0" },
  { name: "Sea Green", hex: "#2E8B6E" },
  { name: "Rama Green", hex: "#1F8A8A" },
  { name: "Sky Blue", hex: "#7EC3E8" },
  { name: "Firozi", hex: "#2BB3C0" },
  { name: "Royal Blue", hex: "#2C4CB0" },
  { name: "Purple", hex: "#5E2A84" },
  { name: "Lavender", hex: "#B7A3D9" },
  { name: "Mauve", hex: "#9C6A8C" },
  { name: "Brown", hex: "#6B4226" },
  { name: "Beige", hex: "#D9C4A3" },
  { name: "Cream", hex: "#F3E7CF" },
  { name: "Off White", hex: "#F5F1E8" },
  { name: "White", hex: "#FFFFFF" },
  { name: "Grey", hex: "#8A8A8A" },
  { name: "Silver", hex: "#C7C9CC" },
];
